const PHOTO_PANELS = [
    "Ridgeline_North", 
    "BuckCanyon_NorthWall", 
    "BuckCanyon_BackWall", 
    "BuckCanyon_SouthWall", 
    "BuckCanyon_NorthWall2", 
    "BuckCanyon_SouthWall",
    "KrisinMesa", 
    "BuckMesa_NorthWall", 
    "Javelina_Amphitheatre", 
    "CaroleCanyon_NW", 
    "CaroleCanyon_Swall_UBC", 
    "P2Canyon_NorthWall", 
    "P2Canyon_SouthWall", 
    "BuckMesaEastFace", 
    "BuckMesa_East", 
    "Terminator2005", 
    "CaroleCanyon_ChannelSW", 
    "CaroleCanyon_ChannelNW", 
    "TerminatorSouth", 
    "Javelina_NorthWall", 
    "Gooseneck", 
    "GoatWall_South", 
    "GoatWall_MidSouth", 
    "GoatWall_MidNorth",
    "GoatWall_North", 
    "CaroleCanyon_Swall", 
    "WesternMesa", 
    "P2Canyon", 
    "P3_longview", 
    "P2P3Canyon_SouthWall", 
    "P3_longview_West", 
    "P3_ConcLobe", 
    "BuckMesa_midWestFace", 
    "P3_Lower", 
    "BloatedAngry_Goat_Canyon_Lower", 
    "Mess_South_of_PipelineRd", 
    "MiddleMesa_EastFace", 
    "SDMR_from_SplitPeak", 
    "SDMR_WestFace", 
    "SplitPeak_EastFace", 
    "BuckMesa_Middle_GreyBand", 
    "SplitPeak_NorthFace", 
    "MysteryCanyon_NorthWall", 
    "P2Canyon_Southwall", 
    "Ridgeline_SouthtoMysteryCanyon", 
    "Ridgeline_SouthtoSplitPeak", 
    "MysteryCanyon_SouthWall", 
    "F5_scour_BtoT", 
    "DMR_fromKM", 
    "P3_maindraw", 
    "West Point Overview_N", 
    "West Point Overview_S", 
    "SeepSpring", 
    "USBV - Gash", 
    "Popocito_panel", 
    "Popo_ChinamansHat", 
    "East Popo", 
    "North West Graben", 
    "ColleenF5Wall2", 
    "Cigar Wall", 
    "Rock Art - EP - Culverts", 
    "SDMR_from_FaultHill",
];

export default PHOTO_PANELS;